site_name: pizzaorder
site_description: Pizza Order Api
repo_url: https://github.com/brsrtc/pizza-order
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/brsrtc">brsrtc</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
