# Generated by Django 2.1.9 on 2020-12-01 20:40

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[['received', 'Received'], ['preparing', 'Preparing'], ['on_delivery', 'On Delivery'], ['delivered', 'Delivered'], ['canceled', 'Canceled'], ['turn_back', 'Turn Back']], db_index=True, default=order.models.OrderStatusEnum('received'), max_length=50, verbose_name='Order Status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.Customer', verbose_name='Customer')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('pizza_size', models.CharField(choices=[['small', 'Small'], ['medium', 'Medium'], ['large', 'Large']], db_index=True, max_length=50, verbose_name='Size')),
                ('pizza', models.CharField(choices=[['margarita', 'Margarita'], ['marinara', 'Marinara'], ['salami', 'Salami']], db_index=True, max_length=50, verbose_name='Pizza Flavor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Order', verbose_name='Order')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
